/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-10-03 at 01:30:50 UTC 
 * Modify at your own risk.
 */

package com.kindhat.service.item.itemrequestendpoint.model;

/**
 * Model definition for ItemRequest.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the itemrequestendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ItemRequest extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key key;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String requestAvailability;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime requestDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String requestLength;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String requestMessage;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userName;

  /**
   * @return value or {@code null} for none
   */
  public Key getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public ItemRequest setKey(Key key) {
    this.key = key;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getRequestAvailability() {
    return requestAvailability;
  }

  /**
   * @param requestAvailability requestAvailability or {@code null} for none
   */
  public ItemRequest setRequestAvailability(java.lang.String requestAvailability) {
    this.requestAvailability = requestAvailability;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getRequestDate() {
    return requestDate;
  }

  /**
   * @param requestDate requestDate or {@code null} for none
   */
  public ItemRequest setRequestDate(com.google.api.client.util.DateTime requestDate) {
    this.requestDate = requestDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getRequestLength() {
    return requestLength;
  }

  /**
   * @param requestLength requestLength or {@code null} for none
   */
  public ItemRequest setRequestLength(java.lang.String requestLength) {
    this.requestLength = requestLength;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getRequestMessage() {
    return requestMessage;
  }

  /**
   * @param requestMessage requestMessage or {@code null} for none
   */
  public ItemRequest setRequestMessage(java.lang.String requestMessage) {
    this.requestMessage = requestMessage;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserId() {
    return userId;
  }

  /**
   * @param userId userId or {@code null} for none
   */
  public ItemRequest setUserId(java.lang.String userId) {
    this.userId = userId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserName() {
    return userName;
  }

  /**
   * @param userName userName or {@code null} for none
   */
  public ItemRequest setUserName(java.lang.String userName) {
    this.userName = userName;
    return this;
  }

  @Override
  public ItemRequest set(String fieldName, Object value) {
    return (ItemRequest) super.set(fieldName, value);
  }

  @Override
  public ItemRequest clone() {
    return (ItemRequest) super.clone();
  }

}
