/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-10-03 at 01:30:50 UTC 
 * Modify at your own risk.
 */

package com.kindhat.service.item.itemrequestendpoint;

/**
 * Service definition for Itemrequestendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ItemrequestendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Itemrequestendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the itemrequestendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://kindhat-service.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "itemrequestendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Itemrequestendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Itemrequestendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getItemRequest".
   *
   * This request holds the parameters needed by the itemrequestendpoint server.  After setting any
   * optional parameters, call the {@link GetItemRequest#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetItemRequest getItemRequest(java.lang.Long id) throws java.io.IOException {
    GetItemRequest result = new GetItemRequest(id);
    initialize(result);
    return result;
  }

  public class GetItemRequest extends ItemrequestendpointRequest<com.kindhat.service.item.itemrequestendpoint.model.ItemRequest> {

    private static final String REST_PATH = "itemrequest/{id}";

    /**
     * Create a request for the method "getItemRequest".
     *
     * This request holds the parameters needed by the the itemrequestendpoint server.  After setting
     * any optional parameters, call the {@link GetItemRequest#execute()} method to invoke the remote
     * operation. <p> {@link GetItemRequest#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetItemRequest(java.lang.Long id) {
      super(Itemrequestendpoint.this, "GET", REST_PATH, null, com.kindhat.service.item.itemrequestendpoint.model.ItemRequest.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetItemRequest setAlt(java.lang.String alt) {
      return (GetItemRequest) super.setAlt(alt);
    }

    @Override
    public GetItemRequest setFields(java.lang.String fields) {
      return (GetItemRequest) super.setFields(fields);
    }

    @Override
    public GetItemRequest setKey(java.lang.String key) {
      return (GetItemRequest) super.setKey(key);
    }

    @Override
    public GetItemRequest setOauthToken(java.lang.String oauthToken) {
      return (GetItemRequest) super.setOauthToken(oauthToken);
    }

    @Override
    public GetItemRequest setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetItemRequest) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetItemRequest setQuotaUser(java.lang.String quotaUser) {
      return (GetItemRequest) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetItemRequest setUserIp(java.lang.String userIp) {
      return (GetItemRequest) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetItemRequest setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetItemRequest set(String parameterName, Object value) {
      return (GetItemRequest) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertItemRequest".
   *
   * This request holds the parameters needed by the itemrequestendpoint server.  After setting any
   * optional parameters, call the {@link InsertItemRequest#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.kindhat.service.item.itemrequestendpoint.model.ItemRequest}
   * @return the request
   */
  public InsertItemRequest insertItemRequest(com.kindhat.service.item.itemrequestendpoint.model.ItemRequest content) throws java.io.IOException {
    InsertItemRequest result = new InsertItemRequest(content);
    initialize(result);
    return result;
  }

  public class InsertItemRequest extends ItemrequestendpointRequest<com.kindhat.service.item.itemrequestendpoint.model.ItemRequest> {

    private static final String REST_PATH = "itemrequest";

    /**
     * Create a request for the method "insertItemRequest".
     *
     * This request holds the parameters needed by the the itemrequestendpoint server.  After setting
     * any optional parameters, call the {@link InsertItemRequest#execute()} method to invoke the
     * remote operation. <p> {@link InsertItemRequest#initialize(com.google.api.client.googleapis.serv
     * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.kindhat.service.item.itemrequestendpoint.model.ItemRequest}
     * @since 1.13
     */
    protected InsertItemRequest(com.kindhat.service.item.itemrequestendpoint.model.ItemRequest content) {
      super(Itemrequestendpoint.this, "POST", REST_PATH, content, com.kindhat.service.item.itemrequestendpoint.model.ItemRequest.class);
    }

    @Override
    public InsertItemRequest setAlt(java.lang.String alt) {
      return (InsertItemRequest) super.setAlt(alt);
    }

    @Override
    public InsertItemRequest setFields(java.lang.String fields) {
      return (InsertItemRequest) super.setFields(fields);
    }

    @Override
    public InsertItemRequest setKey(java.lang.String key) {
      return (InsertItemRequest) super.setKey(key);
    }

    @Override
    public InsertItemRequest setOauthToken(java.lang.String oauthToken) {
      return (InsertItemRequest) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertItemRequest setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertItemRequest) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertItemRequest setQuotaUser(java.lang.String quotaUser) {
      return (InsertItemRequest) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertItemRequest setUserIp(java.lang.String userIp) {
      return (InsertItemRequest) super.setUserIp(userIp);
    }

    @Override
    public InsertItemRequest set(String parameterName, Object value) {
      return (InsertItemRequest) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listItemRequest".
   *
   * This request holds the parameters needed by the itemrequestendpoint server.  After setting any
   * optional parameters, call the {@link ListItemRequest#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListItemRequest listItemRequest() throws java.io.IOException {
    ListItemRequest result = new ListItemRequest();
    initialize(result);
    return result;
  }

  public class ListItemRequest extends ItemrequestendpointRequest<com.kindhat.service.item.itemrequestendpoint.model.CollectionResponseItemRequest> {

    private static final String REST_PATH = "itemrequest";

    /**
     * Create a request for the method "listItemRequest".
     *
     * This request holds the parameters needed by the the itemrequestendpoint server.  After setting
     * any optional parameters, call the {@link ListItemRequest#execute()} method to invoke the remote
     * operation. <p> {@link ListItemRequest#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListItemRequest() {
      super(Itemrequestendpoint.this, "GET", REST_PATH, null, com.kindhat.service.item.itemrequestendpoint.model.CollectionResponseItemRequest.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListItemRequest setAlt(java.lang.String alt) {
      return (ListItemRequest) super.setAlt(alt);
    }

    @Override
    public ListItemRequest setFields(java.lang.String fields) {
      return (ListItemRequest) super.setFields(fields);
    }

    @Override
    public ListItemRequest setKey(java.lang.String key) {
      return (ListItemRequest) super.setKey(key);
    }

    @Override
    public ListItemRequest setOauthToken(java.lang.String oauthToken) {
      return (ListItemRequest) super.setOauthToken(oauthToken);
    }

    @Override
    public ListItemRequest setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListItemRequest) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListItemRequest setQuotaUser(java.lang.String quotaUser) {
      return (ListItemRequest) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListItemRequest setUserIp(java.lang.String userIp) {
      return (ListItemRequest) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListItemRequest setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListItemRequest setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListItemRequest set(String parameterName, Object value) {
      return (ListItemRequest) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeItemRequest".
   *
   * This request holds the parameters needed by the itemrequestendpoint server.  After setting any
   * optional parameters, call the {@link RemoveItemRequest#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveItemRequest removeItemRequest(java.lang.Long id) throws java.io.IOException {
    RemoveItemRequest result = new RemoveItemRequest(id);
    initialize(result);
    return result;
  }

  public class RemoveItemRequest extends ItemrequestendpointRequest<Void> {

    private static final String REST_PATH = "itemrequest/{id}";

    /**
     * Create a request for the method "removeItemRequest".
     *
     * This request holds the parameters needed by the the itemrequestendpoint server.  After setting
     * any optional parameters, call the {@link RemoveItemRequest#execute()} method to invoke the
     * remote operation. <p> {@link RemoveItemRequest#initialize(com.google.api.client.googleapis.serv
     * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveItemRequest(java.lang.Long id) {
      super(Itemrequestendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveItemRequest setAlt(java.lang.String alt) {
      return (RemoveItemRequest) super.setAlt(alt);
    }

    @Override
    public RemoveItemRequest setFields(java.lang.String fields) {
      return (RemoveItemRequest) super.setFields(fields);
    }

    @Override
    public RemoveItemRequest setKey(java.lang.String key) {
      return (RemoveItemRequest) super.setKey(key);
    }

    @Override
    public RemoveItemRequest setOauthToken(java.lang.String oauthToken) {
      return (RemoveItemRequest) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveItemRequest setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveItemRequest) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveItemRequest setQuotaUser(java.lang.String quotaUser) {
      return (RemoveItemRequest) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveItemRequest setUserIp(java.lang.String userIp) {
      return (RemoveItemRequest) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveItemRequest setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveItemRequest set(String parameterName, Object value) {
      return (RemoveItemRequest) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateItemRequest".
   *
   * This request holds the parameters needed by the itemrequestendpoint server.  After setting any
   * optional parameters, call the {@link UpdateItemRequest#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.kindhat.service.item.itemrequestendpoint.model.ItemRequest}
   * @return the request
   */
  public UpdateItemRequest updateItemRequest(com.kindhat.service.item.itemrequestendpoint.model.ItemRequest content) throws java.io.IOException {
    UpdateItemRequest result = new UpdateItemRequest(content);
    initialize(result);
    return result;
  }

  public class UpdateItemRequest extends ItemrequestendpointRequest<com.kindhat.service.item.itemrequestendpoint.model.ItemRequest> {

    private static final String REST_PATH = "itemrequest";

    /**
     * Create a request for the method "updateItemRequest".
     *
     * This request holds the parameters needed by the the itemrequestendpoint server.  After setting
     * any optional parameters, call the {@link UpdateItemRequest#execute()} method to invoke the
     * remote operation. <p> {@link UpdateItemRequest#initialize(com.google.api.client.googleapis.serv
     * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.kindhat.service.item.itemrequestendpoint.model.ItemRequest}
     * @since 1.13
     */
    protected UpdateItemRequest(com.kindhat.service.item.itemrequestendpoint.model.ItemRequest content) {
      super(Itemrequestendpoint.this, "PUT", REST_PATH, content, com.kindhat.service.item.itemrequestendpoint.model.ItemRequest.class);
    }

    @Override
    public UpdateItemRequest setAlt(java.lang.String alt) {
      return (UpdateItemRequest) super.setAlt(alt);
    }

    @Override
    public UpdateItemRequest setFields(java.lang.String fields) {
      return (UpdateItemRequest) super.setFields(fields);
    }

    @Override
    public UpdateItemRequest setKey(java.lang.String key) {
      return (UpdateItemRequest) super.setKey(key);
    }

    @Override
    public UpdateItemRequest setOauthToken(java.lang.String oauthToken) {
      return (UpdateItemRequest) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateItemRequest setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateItemRequest) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateItemRequest setQuotaUser(java.lang.String quotaUser) {
      return (UpdateItemRequest) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateItemRequest setUserIp(java.lang.String userIp) {
      return (UpdateItemRequest) super.setUserIp(userIp);
    }

    @Override
    public UpdateItemRequest set(String parameterName, Object value) {
      return (UpdateItemRequest) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Itemrequestendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Itemrequestendpoint}. */
    @Override
    public Itemrequestendpoint build() {
      return new Itemrequestendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ItemrequestendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setItemrequestendpointRequestInitializer(
        ItemrequestendpointRequestInitializer itemrequestendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(itemrequestendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
