/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-04-27 at 21:55:06 UTC 
 * Modify at your own risk.
 */

package com.kindhat.service.configuration.configurationendpoint;

/**
 * Service definition for Configurationendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ConfigurationendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Configurationendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the configurationendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://kindhat-service.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "configurationendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Configurationendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Configurationendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getAllConfiguration".
   *
   * This request holds the parameters needed by the configurationendpoint server.  After setting any
   * optional parameters, call the {@link GetAllConfiguration#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public GetAllConfiguration getAllConfiguration() throws java.io.IOException {
    GetAllConfiguration result = new GetAllConfiguration();
    initialize(result);
    return result;
  }

  public class GetAllConfiguration extends ConfigurationendpointRequest<com.kindhat.service.configuration.configurationendpoint.model.ConfigurationCollection> {

    private static final String REST_PATH = "configurationcollection";

    /**
     * Create a request for the method "getAllConfiguration".
     *
     * This request holds the parameters needed by the the configurationendpoint server.  After
     * setting any optional parameters, call the {@link GetAllConfiguration#execute()} method to
     * invoke the remote operation. <p> {@link GetAllConfiguration#initialize(com.google.api.client.go
     * ogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected GetAllConfiguration() {
      super(Configurationendpoint.this, "GET", REST_PATH, null, com.kindhat.service.configuration.configurationendpoint.model.ConfigurationCollection.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetAllConfiguration setAlt(java.lang.String alt) {
      return (GetAllConfiguration) super.setAlt(alt);
    }

    @Override
    public GetAllConfiguration setFields(java.lang.String fields) {
      return (GetAllConfiguration) super.setFields(fields);
    }

    @Override
    public GetAllConfiguration setKey(java.lang.String key) {
      return (GetAllConfiguration) super.setKey(key);
    }

    @Override
    public GetAllConfiguration setOauthToken(java.lang.String oauthToken) {
      return (GetAllConfiguration) super.setOauthToken(oauthToken);
    }

    @Override
    public GetAllConfiguration setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetAllConfiguration) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetAllConfiguration setQuotaUser(java.lang.String quotaUser) {
      return (GetAllConfiguration) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetAllConfiguration setUserIp(java.lang.String userIp) {
      return (GetAllConfiguration) super.setUserIp(userIp);
    }

    @Override
    public GetAllConfiguration set(String parameterName, Object value) {
      return (GetAllConfiguration) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getConfiguration".
   *
   * This request holds the parameters needed by the configurationendpoint server.  After setting any
   * optional parameters, call the {@link GetConfiguration#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetConfiguration getConfiguration(java.lang.Long id) throws java.io.IOException {
    GetConfiguration result = new GetConfiguration(id);
    initialize(result);
    return result;
  }

  public class GetConfiguration extends ConfigurationendpointRequest<com.kindhat.service.configuration.configurationendpoint.model.Configuration> {

    private static final String REST_PATH = "configuration/{id}";

    /**
     * Create a request for the method "getConfiguration".
     *
     * This request holds the parameters needed by the the configurationendpoint server.  After
     * setting any optional parameters, call the {@link GetConfiguration#execute()} method to invoke
     * the remote operation. <p> {@link GetConfiguration#initialize(com.google.api.client.googleapis.s
     * ervices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetConfiguration(java.lang.Long id) {
      super(Configurationendpoint.this, "GET", REST_PATH, null, com.kindhat.service.configuration.configurationendpoint.model.Configuration.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetConfiguration setAlt(java.lang.String alt) {
      return (GetConfiguration) super.setAlt(alt);
    }

    @Override
    public GetConfiguration setFields(java.lang.String fields) {
      return (GetConfiguration) super.setFields(fields);
    }

    @Override
    public GetConfiguration setKey(java.lang.String key) {
      return (GetConfiguration) super.setKey(key);
    }

    @Override
    public GetConfiguration setOauthToken(java.lang.String oauthToken) {
      return (GetConfiguration) super.setOauthToken(oauthToken);
    }

    @Override
    public GetConfiguration setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetConfiguration) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetConfiguration setQuotaUser(java.lang.String quotaUser) {
      return (GetConfiguration) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetConfiguration setUserIp(java.lang.String userIp) {
      return (GetConfiguration) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetConfiguration setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetConfiguration set(String parameterName, Object value) {
      return (GetConfiguration) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertConfiguration".
   *
   * This request holds the parameters needed by the configurationendpoint server.  After setting any
   * optional parameters, call the {@link InsertConfiguration#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.kindhat.service.configuration.configurationendpoint.model.Configuration}
   * @return the request
   */
  public InsertConfiguration insertConfiguration(com.kindhat.service.configuration.configurationendpoint.model.Configuration content) throws java.io.IOException {
    InsertConfiguration result = new InsertConfiguration(content);
    initialize(result);
    return result;
  }

  public class InsertConfiguration extends ConfigurationendpointRequest<com.kindhat.service.configuration.configurationendpoint.model.Configuration> {

    private static final String REST_PATH = "configuration";

    /**
     * Create a request for the method "insertConfiguration".
     *
     * This request holds the parameters needed by the the configurationendpoint server.  After
     * setting any optional parameters, call the {@link InsertConfiguration#execute()} method to
     * invoke the remote operation. <p> {@link InsertConfiguration#initialize(com.google.api.client.go
     * ogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.kindhat.service.configuration.configurationendpoint.model.Configuration}
     * @since 1.13
     */
    protected InsertConfiguration(com.kindhat.service.configuration.configurationendpoint.model.Configuration content) {
      super(Configurationendpoint.this, "POST", REST_PATH, content, com.kindhat.service.configuration.configurationendpoint.model.Configuration.class);
    }

    @Override
    public InsertConfiguration setAlt(java.lang.String alt) {
      return (InsertConfiguration) super.setAlt(alt);
    }

    @Override
    public InsertConfiguration setFields(java.lang.String fields) {
      return (InsertConfiguration) super.setFields(fields);
    }

    @Override
    public InsertConfiguration setKey(java.lang.String key) {
      return (InsertConfiguration) super.setKey(key);
    }

    @Override
    public InsertConfiguration setOauthToken(java.lang.String oauthToken) {
      return (InsertConfiguration) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertConfiguration setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertConfiguration) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertConfiguration setQuotaUser(java.lang.String quotaUser) {
      return (InsertConfiguration) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertConfiguration setUserIp(java.lang.String userIp) {
      return (InsertConfiguration) super.setUserIp(userIp);
    }

    @Override
    public InsertConfiguration set(String parameterName, Object value) {
      return (InsertConfiguration) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listConfiguration".
   *
   * This request holds the parameters needed by the configurationendpoint server.  After setting any
   * optional parameters, call the {@link ListConfiguration#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListConfiguration listConfiguration() throws java.io.IOException {
    ListConfiguration result = new ListConfiguration();
    initialize(result);
    return result;
  }

  public class ListConfiguration extends ConfigurationendpointRequest<com.kindhat.service.configuration.configurationendpoint.model.CollectionResponseConfiguration> {

    private static final String REST_PATH = "configuration";

    /**
     * Create a request for the method "listConfiguration".
     *
     * This request holds the parameters needed by the the configurationendpoint server.  After
     * setting any optional parameters, call the {@link ListConfiguration#execute()} method to invoke
     * the remote operation. <p> {@link ListConfiguration#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListConfiguration() {
      super(Configurationendpoint.this, "GET", REST_PATH, null, com.kindhat.service.configuration.configurationendpoint.model.CollectionResponseConfiguration.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListConfiguration setAlt(java.lang.String alt) {
      return (ListConfiguration) super.setAlt(alt);
    }

    @Override
    public ListConfiguration setFields(java.lang.String fields) {
      return (ListConfiguration) super.setFields(fields);
    }

    @Override
    public ListConfiguration setKey(java.lang.String key) {
      return (ListConfiguration) super.setKey(key);
    }

    @Override
    public ListConfiguration setOauthToken(java.lang.String oauthToken) {
      return (ListConfiguration) super.setOauthToken(oauthToken);
    }

    @Override
    public ListConfiguration setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListConfiguration) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListConfiguration setQuotaUser(java.lang.String quotaUser) {
      return (ListConfiguration) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListConfiguration setUserIp(java.lang.String userIp) {
      return (ListConfiguration) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListConfiguration setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListConfiguration setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListConfiguration set(String parameterName, Object value) {
      return (ListConfiguration) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateConfiguration".
   *
   * This request holds the parameters needed by the configurationendpoint server.  After setting any
   * optional parameters, call the {@link UpdateConfiguration#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.kindhat.service.configuration.configurationendpoint.model.Configuration}
   * @return the request
   */
  public UpdateConfiguration updateConfiguration(com.kindhat.service.configuration.configurationendpoint.model.Configuration content) throws java.io.IOException {
    UpdateConfiguration result = new UpdateConfiguration(content);
    initialize(result);
    return result;
  }

  public class UpdateConfiguration extends ConfigurationendpointRequest<com.kindhat.service.configuration.configurationendpoint.model.Configuration> {

    private static final String REST_PATH = "configuration";

    /**
     * Create a request for the method "updateConfiguration".
     *
     * This request holds the parameters needed by the the configurationendpoint server.  After
     * setting any optional parameters, call the {@link UpdateConfiguration#execute()} method to
     * invoke the remote operation. <p> {@link UpdateConfiguration#initialize(com.google.api.client.go
     * ogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.kindhat.service.configuration.configurationendpoint.model.Configuration}
     * @since 1.13
     */
    protected UpdateConfiguration(com.kindhat.service.configuration.configurationendpoint.model.Configuration content) {
      super(Configurationendpoint.this, "PUT", REST_PATH, content, com.kindhat.service.configuration.configurationendpoint.model.Configuration.class);
    }

    @Override
    public UpdateConfiguration setAlt(java.lang.String alt) {
      return (UpdateConfiguration) super.setAlt(alt);
    }

    @Override
    public UpdateConfiguration setFields(java.lang.String fields) {
      return (UpdateConfiguration) super.setFields(fields);
    }

    @Override
    public UpdateConfiguration setKey(java.lang.String key) {
      return (UpdateConfiguration) super.setKey(key);
    }

    @Override
    public UpdateConfiguration setOauthToken(java.lang.String oauthToken) {
      return (UpdateConfiguration) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateConfiguration setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateConfiguration) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateConfiguration setQuotaUser(java.lang.String quotaUser) {
      return (UpdateConfiguration) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateConfiguration setUserIp(java.lang.String userIp) {
      return (UpdateConfiguration) super.setUserIp(userIp);
    }

    @Override
    public UpdateConfiguration set(String parameterName, Object value) {
      return (UpdateConfiguration) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Configurationendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Configurationendpoint}. */
    @Override
    public Configurationendpoint build() {
      return new Configurationendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ConfigurationendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setConfigurationendpointRequestInitializer(
        ConfigurationendpointRequestInitializer configurationendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(configurationendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
